on: [issues]
jobs:
  build:
    name: ğŸ¤ Reply
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello there, thank you for opening an Issue ! ğŸ™ğŸ» The team was notified and they will get back to you asap."